# apps/loja-api/base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: loja-api
  labels:
    app: loja-api
spec:
  selector:
    app: loja-api
  ports:
    - name: http-metrics
      port: 8000
      targetPort: 8000
      protocol: TCP
