# apps/loja-api/overlays/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: loja-api-staging
images:
- name: ghcr.io/wandermaia/loja-api
  newName: ghcr.io/wandermaia/loja-api
  newTag: 7352c73
